import type { AccountPerformance } from '../google-ads/types'
import { formatCurrency, formatNumber } from '../utils'

export function generateEmailTemplate(reportData: AccountPerformance[], reportDate: Date): string {
  const formattedDate = reportDate.toLocaleDateString('en-AU', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const totalSpend = reportData.reduce((sum, account) => sum + account.yesterday.cost, 0)
  const totalConversions = reportData.reduce((sum, account) => sum + account.yesterday.conversions, 0)
  const totalClicks = reportData.reduce((sum, account) => sum + account.yesterday.clicks, 0)

  const accountsHtml = reportData
    .map(
      (account) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #fde68a;">
        <strong>${account.name}</strong><br>
        <span style="color: #6b7280; font-size: 12px;">ID: ${account.id}</span>
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #fde68a; text-align: right;">
        ${formatCurrency(account.yesterday.cost, account.currency)}
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #fde68a; text-align: right;">
        ${Math.round(account.yesterday.conversions)}
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #fde68a; text-align: right;">
        ${formatNumber(account.yesterday.clicks)}
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #fde68a; text-align: right;">
        ${formatNumber(account.yesterday.impressions)}
      </td>
    </tr>
  `
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily MCC Report - ${formattedDate}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #fefce8;">
  <div style="max-width: 800px; margin: 0 auto; padding: 40px 20px;">

    <!-- Header -->
    <div style="background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border-radius: 16px; padding: 32px; margin-bottom: 32px; text-align: center;">
      <h1 style="margin: 0 0 8px 0; color: #111827; font-size: 28px;">Daily MCC Report</h1>
      <p style="margin: 0; color: #4b5563; font-size: 16px;">${formattedDate}</p>
    </div>

    <!-- Summary Cards -->
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px;">
      <div style="background: white; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <p style="margin: 0 0 8px 0; color: #6b7280; font-size: 14px;">Total Spend</p>
        <p style="margin: 0; color: #111827; font-size: 24px; font-weight: bold;">${formatCurrency(totalSpend)}</p>
      </div>
      <div style="background: white; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <p style="margin: 0 0 8px 0; color: #6b7280; font-size: 14px;">Conversions</p>
        <p style="margin: 0; color: #111827; font-size: 24px; font-weight: bold;">${Math.round(totalConversions)}</p>
      </div>
      <div style="background: white; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <p style="margin: 0 0 8px 0; color: #6b7280; font-size: 14px;">Clicks</p>
        <p style="margin: 0; color: #111827; font-size: 24px; font-weight: bold;">${formatNumber(totalClicks)}</p>
      </div>
    </div>

    <!-- Account Performance Table -->
    <div style="background: white; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 32px;">
      <h2 style="margin: 0 0 20px 0; color: #111827; font-size: 20px;">Account Performance</h2>
      <table style="width: 100%; border-collapse: collapse;">
        <thead>
          <tr style="background-color: #fef3c7;">
            <th style="padding: 12px; text-align: left; font-weight: 600; color: #111827;">Account</th>
            <th style="padding: 12px; text-align: right; font-weight: 600; color: #111827;">Spend</th>
            <th style="padding: 12px; text-align: right; font-weight: 600; color: #111827;">Conversions</th>
            <th style="padding: 12px; text-align: right; font-weight: 600; color: #111827;">Clicks</th>
            <th style="padding: 12px; text-align: right; font-weight: 600; color: #111827;">Impressions</th>
          </tr>
        </thead>
        <tbody>
          ${accountsHtml}
        </tbody>
      </table>
    </div>

    <!-- Footer -->
    <div style="text-align: center; color: #6b7280; font-size: 14px;">
      <p style="margin: 0;">
        Generated by <strong>Beech PPC AI Agent</strong><br>
        <a href="https://beechppc.com" style="color: #f59e0b; text-decoration: none;">www.beechppc.com</a>
      </p>
    </div>

  </div>
</body>
</html>
  `
}
